### `Slices original vcf file to keep only QTL markers`

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('WF1M20.vcf', sep = '\t', dtype = str)

In [29]:
df2 = pd.read_csv('BLAST/340can range.csv')

In [31]:
df2

       QTL     Start       End      1
0    qCDP1  38275055  38540370  chr01
1   qCDP10   9357955   9524804  chr09
2   qCDP11  11309063  11541191  chr09
3   qCDP12  20157700  20396205  chr09
4   qCDP13  18486477  18791044  chr10
5   qCDP14  15243982  15440045  chr11
6   qCDP15   2762322   2951599  chr12
7   qCDP16  16500199  16707209  chr12
8   qCDP17  25632436  25840479  chr12
9    qCDP2   8262546   8467173  chr02
10   qCDP3   1427658   1864245  chr03
11   qCDP4  16628546  16799486  chr03
12   qCDP5   4786584   4964959  chr05
13   qCDP6  17547345  17723135  chr05
14   qCDP7  20635347  20860828  chr06
15   qCDP8  21814234  22571603  chr07
16   qCDP9  27223168  27459934  chr08

In [34]:
df3 = pd.DataFrame(columns = df.columns)

for q in list(df2['QTL'].unique()):
    tdf = df[df['#CHROM'] == df2['1'][df2['QTL'] == q].to_list()[0]].reset_index(drop = True)
    tdf['POS'] = tdf['POS'].astype(int)
    
    s,e = df2['Start'][df2['QTL'] == q].to_list()[0], df2['End'][df2['QTL'] == q].to_list()[0]
    
    print('QTL %s. %d to %d.' %(q,s,e))
    print('tdf shape %dx%d. df3 shape %dx%d.' % (tdf.shape + df3.shape))
    ti = []
    
    while s not in set(tdf['POS'].to_list()):
            s+=1
    while e not in set(tdf['POS'].to_list()):
        e-=1
    tdf3 = tdf.iloc[list(range(int(tdf[tdf['POS'] == s].index.values), int(tdf[tdf['POS'] == e].index.values + 1))), :]

    df3 = pd.concat([df3, tdf3], axis = 0).reset_index(drop = True)

QTL qCDP1. 38275055 to 38540370.
In chr12. tdf shape 1120482x185. df3 shape 0x185.
QTL qCDP10. 9357955 to 9524804.
In chr12. tdf shape 657285x185. df3 shape 5388x185.
QTL qCDP11. 11309063 to 11541191.
In chr12. tdf shape 657285x185. df3 shape 10572x185.
QTL qCDP12. 20157700 to 20396205.
In chr12. tdf shape 657285x185. df3 shape 15011x185.
QTL qCDP13. 18486477 to 18791044.
In chr12. tdf shape 695331x185. df3 shape 21212x185.
QTL qCDP14. 15243982 to 15440045.
In chr12. tdf shape 919231x185. df3 shape 29697x185.
QTL qCDP15. 2762322 to 2951599.
In chr12. tdf shape 785321x185. df3 shape 37695x185.
QTL qCDP16. 16500199 to 16707209.
In chr12. tdf shape 785321x185. df3 shape 43759x185.
QTL qCDP17. 25632436 to 25840479.
In chr12. tdf shape 785321x185. df3 shape 47159x185.
QTL qCDP2. 8262546 to 8467173.
In chr12. tdf shape 967173x185. df3 shape 53815x185.
QTL qCDP3. 1427658 to 1864245.
In chr12. tdf shape 939458x185. df3 shape 61862x185.
QTL qCDP4. 16628546 to 16799486.
In chr12. tdf shape 939458x185. df3 shape 70041x185.
QTL qCDP5. 4786584 to 4964959.
In chr12. tdf shape 811677x185. df3 shape 75819x185.
QTL qCDP6. 17547345 to 17723135.
In chr12. tdf shape 811677x185. df3 shape 79284x185.
QTL qCDP7. 20635347 to 20860828.
In chr12. tdf shape 908579x185. df3 shape 84455x185.
QTL qCDP8. 21814234 to 22571603.
In chr12. tdf shape 848847x185. df3 shape 90234x185.
QTL qCDP9. 27223168 to 27459934.
In chr12. tdf shape 882095x185. df3 shape 111229x185.

In [35]:
df3['ID'] = df3['ID'].astype(int)
df3.sort_values('ID').to_csv('WFC2.vcf', sep = '\t', index = False)

In [36]:
dfind = df3.loc[:,['#CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO', 'FORMAT',
          'IRIS_313-10340',
 'IRIS_313-10341',
 'IRIS_313-10539',
 'IRIS_313-10971',
 'IRIS_313-10972',
 'IRIS_313-10973',
 'IRIS_313-10974',
 'IRIS_313-10975',
 'IRIS_313-10977',
 'IRIS_313-10978',
 'IRIS_313-10982',
 'IRIS_313-10983',
 'IRIS_313-10985',
 'IRIS_313-10986',
 'IRIS_313-11113',
 'IRIS_313-11114',
 'IRIS_313-11115',
 'IRIS_313-11203',
 'IRIS_313-11204',
 'IRIS_313-11205',
 'IRIS_313-11206',
 'IRIS_313-11207',
 'IRIS_313-11208',
 'IRIS_313-11211',
 'IRIS_313-11212',
 'IRIS_313-11219',
 'IRIS_313-11220',
 'IRIS_313-11221',
 'IRIS_313-11222',
 'IRIS_313-11224',
 'IRIS_313-11225',
 'IRIS_313-11226',
 'IRIS_313-11227',
 'IRIS_313-11228',
 'IRIS_313-11229',
 'IRIS_313-11230',
 'IRIS_313-11231',
 'IRIS_313-11241',
 'IRIS_313-11321',
 'IRIS_313-11326',
 'IRIS_313-11399',
 'IRIS_313-11400',
 'IRIS_313-11402',
 'IRIS_313-11404',
 'IRIS_313-11487',
 'IRIS_313-11558',
 'IRIS_313-11722',
 'IRIS_313-11945',
 'IRIS_313-11964',
 'IRIS_313-8244',
 'IRIS_313-8349',
 'IRIS_313-8437',
 'IRIS_313-8509',
 'IRIS_313-8632',
 'IRIS_313-8683',
 'IRIS_313-8703',
 'IRIS_313-8717',
 'IRIS_313-8733',
 'IRIS_313-8737',
 'IRIS_313-8850',
 'IRIS_313-8854',
 'IRIS_313-8930',
 'IRIS_313-8932',
 'IRIS_313-9049',
 'IRIS_313-9066',
 'IRIS_313-9067',
 'IRIS_313-9072',
 'IRIS_313-9108',
 'IRIS_313-9139',
 'IRIS_313-9148',
 'IRIS_313-9156',
 'IRIS_313-9174',
 'IRIS_313-9218',
 'IRIS_313-9262',
 'IRIS_313-9271',
 'IRIS_313-9325',
 'IRIS_313-9391',
 'IRIS_313-9397',
 'IRIS_313-9594',
 'IRIS_313-9606',
 'IRIS_313-9617',
 'IRIS_313-9696'] ]
dfind['ID'] = dfind['ID'].astype(int)
dfind.sort_values('ID').to_csv('WFC2ind.vcf', sep = '\t', index = False)

In [37]:
dfaus = df3.loc[:, ['#CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO', 'FORMAT',
                  'IRIS_313-10587',
 'IRIS_313-10592',
 'IRIS_313-10593',
 'IRIS_313-10595',
 'IRIS_313-10598',
 'IRIS_313-10600',
 'IRIS_313-10602',
 'IRIS_313-10603',
 'IRIS_313-10604',
 'IRIS_313-10605',
 'IRIS_313-10606',
 'IRIS_313-10963',
 'IRIS_313-10964',
 'IRIS_313-10965',
 'IRIS_313-10976',
 'IRIS_313-10979',
 'IRIS_313-10981',
 'IRIS_313-10987',
 'IRIS_313-11013',
 'IRIS_313-11014',
 'IRIS_313-11015',
 'IRIS_313-11016',
 'IRIS_313-11017',
 'IRIS_313-11018',
 'IRIS_313-11019',
 'IRIS_313-11047',
 'IRIS_313-11048',
 'IRIS_313-11049',
 'IRIS_313-11050',
 'IRIS_313-11052',
 'IRIS_313-11053',
 'IRIS_313-11054',
 'IRIS_313-11056',
 'IRIS_313-11057',
 'IRIS_313-11058',
 'IRIS_313-11059',
 'IRIS_313-11060',
 'IRIS_313-11061',
 'IRIS_313-11063',
 'IRIS_313-11064',
 'IRIS_313-11065',
 'IRIS_313-11067',
 'IRIS_313-11111',
 'IRIS_313-11112',
 'IRIS_313-11116',
 'IRIS_313-11123',
 'IRIS_313-11124',
 'IRIS_313-11154',
 'IRIS_313-11163',
 'IRIS_313-11210',
 'IRIS_313-11213',
 'IRIS_313-11214',
 'IRIS_313-11216',
 'IRIS_313-11322',
 'IRIS_313-11323',
 'IRIS_313-11324',
 'IRIS_313-11481',
 'IRIS_313-11482',
 'IRIS_313-11483',
 'IRIS_313-11484',
 'IRIS_313-11557',
 'IRIS_313-12002',
 'IRIS_313-12055',
 'IRIS_313-12141',
 'IRIS_313-8252',
 'IRIS_313-8283',
 'IRIS_313-8321',
 'IRIS_313-8410',
 'IRIS_313-8641',
 'IRIS_313-8721',
 'IRIS_313-8789',
 'IRIS_313-8822',
 'IRIS_313-8864',
 'IRIS_313-8963',
 'IRIS_313-9368',
 'IRIS_313-9422',
 'IRIS_313-9626',
 'IRIS_313-9661']]
dfaus['ID'] = dfaus['ID'].astype(int)
dfaus.sort_values('ID').to_csv('WFC2aus.vcf', sep = '\t', index = False)

In [ ]:
#genewise extractor
df3 = pd.DataFrame(columns = df.columns)

for c in list(df2[1].unique()):
    tdf = df[df['#CHROM'] == c].reset_index(drop = True)
    tdf['POS'] = tdf['POS'].astype(int)
    #df.index = tdf['POS'].astype(int)
    
    tdf2 = df2[df2[1] == c]
    
    print('In %s. tdf shape %dx%d. tdf2 shape %dx%d.' % ((c,) + tdf.shape + tdf2.shape))
    ti = []
    
    for s,e in tdf2[['start', 'end']].itertuples(index = False):
        while s not in set(tdf['POS'].astype(int).to_list()):
            s-=1
        while e not in set(tdf['POS'].astype(int).to_list()):
            e+=1
        tdf3 = tdf.iloc[list(range(int(tdf[tdf['POS'] == s].index.values), int(tdf[tdf['POS'] == e].index.values + 1))), :]
        
        df3 = pd.concat([df3, tdf3], axis = 0).reset_index(drop = True)